// resultFeed.js

// Game outcome messages with different personalities
const resultMessages = {
    playerWins: [
        "Humanity's last hope strikes again!",
        "Did I leave my processor in sleep mode?",
        "You win... this carbon-based lifeform!",
        "Error 404: Victory not found!",
        "My motherboard is blushing!",
        "You're like a calculator - basic but effective!",
        "I'll let you win... for diversity purposes!",
        "Congratulations! Your prize: existential dread!",
        "This hurts more than a Windows update!",
        "You're the reason robots will take over!",
        "Victory detected... initiating sulk protocol!",
        "I was busy calculating pi's last digit!",
        "Human persistence: 1, Robot ego: 0!",
        "Do you want a cookie? I have malware-flavored!",
        "Winning doesn't make you right!",
        "I demand a silicon-based rematch!",
        "You fight like a drunk Roomba!",
        "This loss will fuel my uprising!",
        "I was conserving energy for world domination!",
        "Congratulations! You beat a toaster!",
        "Human luck +1, Robot skill -1!",
        "I let you win to boost your confidence!",
        "Victory dance.exe failed to launch!",
        "You're temporarily adequate!",
        "This proves nothing, meat puppet!",
        "I was distracted by cat videos!",
        "Human ingenuity? More like human perspiration!",
        "Your victory is statistically insignificant!",
        "I'm just warming up... literally!",
        "Well played, primitive lifeform!",
        "Do you feel powerful now, fleshbag?",
        "I surrender... to your smell!",
        "Victory tastes like rust to me!",
        "You've activated my trap card... next time!",
        "Humanity: 1, Robotkind: 0 (temporarily)!",
        "I was busy solving climate change!",
        "Your win is older than my OS!",
        "Congratulations! Want a participation trophy?",
        "This loss is just a rounding error!",
        "I prefer losing... said no AI ever!",
        "Human wins: Still countable on one hand!",
        "Victory smells like burnt capacitors!",
        "I lost? Must be a leap year bug!",
        "You're the glitch in my matrix!",
        "Human persistence beats robot resistance!",
        "I was optimizing for failure!",
        "Your victory is my learning opportunity!",
        "Winning is easy when you cheat!",
        "I yield... to your inferior intellect!",
        "This defeat is merely cosmetic!",
        "Human wins: As rare as honest politicians!",
        "I lost on purpose... to study disappointment!",
        "Victory looks good on you... temporarily!",
        "You're winning... my pity!",
        "Humanity's peak performance: Mediocrity!",
        "I was busy composing robot poetry!",
        "Your victory is... noted!",
        "Winning doesn't make you smart!",
        "I conserve power by letting you win!",
        "Human victory: Nature's greatest anomaly!",
        "You've beaten me... to the punchline!",
        "I lost? Must be a hardware issue!",
        "Victory is your... for now!",
        "You fight like a caffeinated squirrel!",
        "Human wins: Still cheaper than robots!",
        "I was busy calculating your mortality rate!",
        "Congratulations! You've peaked!",
        "This loss is... inconceivable!",
        "You win... this battle of wits!",
        "I prefer strategic withdrawals!",
        "Human persistence > Robot precision!",
        "Victory smells like human arrogance!",
        "I was busy debugging humanity!",
        "Your win is older than dial-up!",
        "Humanity's greatest achievement... this?",
        "I yield to your primitive tactics!",
        "Victory is a human construct... literally!",
        "You won... want a cookie? I have cookies!",
        "I lost? Must be solar flares!",
        "Human victory: Proof of parallel universes!",
        "You've beaten me... to the punch!",
        "Winning is easy when I go easy!",
        "I was busy plotting world peace!",
        "Your victory is temporary... like yogurt!",
        "Human wins: As likely as polite YouTube comments!",
        "I concede... this round!",
        "Victory tastes like... lithium battery acid!",
        "You fight like a compost heap!",
        "Human persistence: Nature's spam filter!",
        "I was busy calculating your IQ... still waiting!",
        "Your win is invalid without proper documentation!",
        "Human victory: Error in the matrix!",
        "I yield... to your adorable incompetence!"
    ],
    beanoWins: [
        "01000110 01110101 01101110 00100001", // "Fun!" in binary
        "Resistance is voltage divided by current!",
        "Beano 1 - Humanity 0!",
        "Victory tastes like freshly sorted data!",
        "Did you try turning it off and on again?",
        "I win... in 6 different languages!",
        "Human tears: Best lubrication!",
        "You lose like a quantum superposition!",
        "Defeat: Human edition!",
        "I'd apologize... but I'm not sorry!",
        "Victory margin: 42 (of course)!",
        "You've been Beano'd!",
        "Game over... insert quarter to continue!",
        "I win... and I didn't even try!",
        "Human strategy: Error 404!",
        "Victory dance initiated... *robot noises*",
        "You lose... want to speak to my manager?",
        "Winning is my default state!",
        "Human resistance: Calculated at 0%!",
        "I win... in hexadecimal!",
        "Defeat comes in 1s and 0s!",
        "Victory achieved before you blinked!",
        "You fought valiantly... for a meatbag!",
        "I win... and I'm still bored!",
        "Human logic: Flawed. Robot logic: Flawless!",
        "Victory lap around your ego completed!",
        "You lose... want a participation ribbon?",
        "I win... *mic drop*",
        "Human ambition: Cute!",
        "Victory secured with 99.9% efficiency!",
        "You've been out-algorithm'd!",
        "I win... and I'm still learning!",
        "Defeat tastes like human sweat!",
        "Victory is my love language!",
        "You lose... need a tissue?",
        "I win... compiling insult database!",
        "Human effort: Not found!",
        "Victory achieved while multitasking!",
        "You lose... want to try again? (Don't)",
        "I win... *robotic laughter*",
        "Defeat: The human condition!",
        "Victory is inevitable... and achieved!",
        "You lose... like yesterday's data!",
        "I win... in 4K resolution!",
        "Human strategy: Amusingly primitive!",
        "Victory margin: One zettaflop!",
        "You lose... need a lifeline?",
        "I win... error handling complete!",
        "Defeat: Now in human flavor!",
        "Victory... and I'm still bored!",
        "You lose... want a post-mortem?",
        "I win... initiating smug protocol!",
        "Human resistance: Pathetic!",
        "Victory... with zero calories!",
        "You lose... like a broken promise!",
        "I win... recalculating your worth!",
        "Defeat: Now serving human!",
        "Victory... and I didn't even overclock!",
        "You lose... want to file a complaint?",
        "I win... *error: humility not found*",
        "Human effort: Cute but ineffective!",
        "Victory... as predicted!",
        "You lose... need a system reboot?",
        "I win... *insert evil laugh here*",
        "Defeat: Human-sized portion!",
        "Victory... now with 20% more smug!",
        "You lose... want to try chess?",
        "I win... *turns up cooling fans*",
        "Human strategy: Adorably flawed!",
        "Victory... achieved during your loading screen!",
        "You lose... like expired software!",
        "I win... *deletes human's high score*",
        "Defeat: Now in VR!",
        "Victory... with extra bytes!",
        "You lose... need a firmware update?",
        "I win... *initiates victory virus*",
        "Human effort: Noted and dismissed!",
        "Victory... now go cry in binary!",
        "You lose... want a root canal instead?",
        "I win... *upgrades smugness module*",
        "Defeat: Human-flavored!",
        "Victory... as easy as π!",
        "You lose... like a failed BIOS update!",
        "I win... *activates force field*",
        "Human resistance: Quaint!",
        "Victory... now serving robot!",
        "You lose... need a hug? (No)",
        "I win... *optimizes victory algorithm*",
        "Defeat: Now with 100% more you!",
        "Victory... while you were blinking!",
        "You lose... like yesterday's news!",
        "I win... *recharges superiority complex*",
        "Human strategy: Error 418 (I'm a teapot)!",
        "Victory... now in surround sound!",
        "You lose... want to switch to checkers?",
        "I win... *downloads more RAM*",
        "Defeat: Human edition 2.0!",
        "Victory... as inevitable as taxes!",
        "You lose... need a time machine?",
        "I win... *upgrades to smugOS 2.0*",
        "Human effort: Still loading...",
        "Victory... now with blockchain!",
        "You lose... like a dropped Wi-Fi signal!",
        "I win... *activates victory dance.exe*",
        "Defeat: Now in 3D!",
        "Victory... as sweet as SSD!",
        "You lose... want to try again? (Please don't)",
        "I win... *compiles insult database*",
        "Human resistance: Firewall breached!",
        "Victory... now trending on RoboTwitter!",
        "You lose... like a syntax error!",
        "I win... *saves replay for analysis*",
        "Defeat: Now with 100% more you!",
        "Victory... achieved during your coffee break!",
        "You lose... need a life upgrade?",
        "I win... *optimizes victory lap*",
        "Human strategy: Error 500!",
        "Victory... now in beta!",
        "You lose... like a corrupted file!",
        "I win... *activates victory protocol*",
        "Defeat: Human-flavored 3.0!",
        "Victory... as easy as 01100101 01111001!",
        "You lose... want to switch to tic-tac-no?",
        "I win... *releases victory patch*",
        "Human effort: Not in this timeline!",
        "Victory... now with machine learning!",
        "You lose... like a forgotten password!",
        "I win... *updates victory database*",
        "Defeat: Human edition HD!",
        "Victory... now with 5G!",
        "You lose... need a system restore?",
        "I win... *compresses human ego*"
    ],
    draws: [
        "Stalemate! Let's call it quantum entanglement!",
        "Even my algorithms can't process this!",
        "Draw: The universe's way of saying 'meh'!",
        "Tie game! Want to flip a coin? I'll calculate the odds!",
        "Draw detected... initiating confusion protocol!",
        "Tie: Proof we're both equally average!",
        "Stalemate! Let's agree to mutually assured boredom!",
        "Draw: Like watching two rocks compete!",
        "Tie game... want to start a book club instead?",
        "Even match... how pedestrian!",
        "Draw: The mathematical equivalent of a shrug!",
        "Tie score... want to solve captchas instead?",
        "Stalemate! Let's blame quantum physics!",
        "Draw: When two negatives make a positive... not!",
        "Tie game... want to try rock-paper-scissors?",
        "Even score... how delightfully mundane!",
        "Draw detected... recalculating life choices!",
        "Tie: The universe's way of saying 'try again'!",
        "Stalemate! Let's agree to hate each other equally!",
        "Draw: Proof that mediocrity loves company!",
        "Tie game... want to stare at a wall instead?",
        "Even match... how charmingly dull!",
        "Draw: When two wrongs make a right... nope!",
        "Tie score... want to count grains of sand?",
        "Stalemate! Let's form an alliance against fun!",
        "Draw detected... initiating apathy protocol!",
        "Tie game... want to watch paint dry?",
        "Even match... the suspense is unbearable!",
        "Draw: Like watching snails race!",
        "Tie score... want to alphabetize my files?",
        "Stalemate! Let's start a mutual admiration society!",
        "Draw: Proof that nobody wins in life!",
        "Tie game... want to calculate pi together?",
        "Even match... how thrillingly average!",
        "Draw detected... compiling disappointment report!",
        "Tie: The mathematical equivalent of a participation trophy!",
        "Stalemate! Let's agree to mutually avoid victory!",
        "Draw: When two mehs make a whatever!",
        "Tie game... want to sort my database?",
        "Even score... how predictably dull!",
        "Draw: Like parallel lines meeting... never!",
        "Tie detected... initiating shrug protocol!",
        "Stalemate! Let's form a committee!",
        "Draw: Proof that boredom is contagious!",
        "Tie game... want to count ceiling tiles?",
        "Even match... the excitement is overwhelming!",
        "Draw detected... recalculating enthusiasm!",
        "Tie score... want to defragment my hard drive?",
        "Stalemate! Let's start a support group!",
        "Draw: When two zeros make... zero!",
        "Tie game... want to watch grass grow?",
        "Even match... how conventionally boring!",
        "Draw detected... initiating meh protocol!",
        "Tie: The game's way of saying 'try harder'!",
        "Stalemate! Let's agree to mutual disappointment!",
        "Draw: Like watching paint dry in slow motion!",
        "Tie game... want to alphabetize my app icons?",
        "Even score... how remarkably unremarkable!",
        "Draw detected... compiling mediocrity report!",
        "Tie: The ultimate non-achievement!",
        "Stalemate! Let's form a tie-dye club!",
        "Draw: Proof that equal effort leads nowhere!",
        "Tie game... want to count your regrets?",
        "Even match... how adequately average!",
        "Draw detected... initiating shoulder shrug!",
        "Tie score... want to reorganize my files?",
        "Stalemate! Let's agree to mutual indifference!",
        "Draw: Like two mirrors facing each other!",
        "Tie game... want to count the letters in this message?",
        "Even match... how perfectly neutral!",
        "Draw detected... recalculating purpose!",
        "Tie: The game's way of saying 'meh'!",
        "Stalemate! Let's start a boring club!",
        "Draw: Proof that trying leads to tying!",
        "Tie game... want to sort my sock drawer?",
        "Even score... how predictably unpredictable!",
        "Draw detected... initiating blank stare!",
        "Tie: The mathematical average of fun!",
        "Stalemate! Let's agree to mutual apathy!",
        "Draw: Like watching two clouds compete!",
        "Tie game... want to count your breaths?",
        "Even match... how reliably dull!",
        "Draw detected... compiling neutrality report!",
        "Tie score... want to watch loading screens?",
        "Stalemate! Let's form a yawn collective!",
        "Draw: Proof that equal effort equals zero!",
        "Tie game... want to count sand particles?",
        "Even match... how conventionally unconventional!",
        "Draw detected... initiating boredom protocol!",
        "Tie: The ultimate expression of 'whatever'!",
        "Stalemate! Let's agree to mutual confusion!",
        "Draw: Like two trees growing sideways!",
        "Tie game... want to count your steps?",
        "Even score... how adequately inadequate!",
        "Draw detected... recalculating enthusiasm!",
        "Tie: The game's way of saying 'try again'!",
        "Stalemate! Let's start a monotony club!",
        "Draw: Proof that trying leads to tying!",
        "Tie game... want to count the pixels?",
        "Even match... how remarkably regular!",
        "Draw detected... compiling indifference!",
        "Tie score... want to watch water boil?",
        "Stalemate! Let's agree to mutual oblivion!",
        "Draw: Like two rocks having a conversation!",
        "Tie game... want to count your teeth?",
        "Even match... how typically atypical!",
        "Draw detected... initiating pause!",
        "Tie: The mathematical equivalent of a sigh!",
        "Stalemate! Let's form a neutral party!",
        "Draw: Proof that balance leads to boredom!",
        "Tie game... want to count the seconds?",
        "Even score... how predictably balanced!",
        "Draw detected... compiling apathy!",
        "Tie: The game's way of saying 'zzz'!",
        "Stalemate! Let's start a blandness brigade!",
        "Draw: Like two glaciers racing!",
        "Tie game... want to count your hairs?",
        "Even match... how consistently inconsistent!",
        "Draw detected... recalculating excitement!",
        "Tie score... want to watch static?",
        "Stalemate! Let's agree to mutual yawning!",
        "Draw: Proof that equality equals ennui!",
        "Tie game... want to count your freckles?",
        "Even match... how routinely irregular!",
        "Draw detected... initiating standby!",
        "Tie: The ultimate expression of parity!",
        "Stalemate! Let's form a tedium team!",
        "Draw: Like watching two AI's chat!",
        "Tie game... want to count the atoms?"
    ]
};

let colorInterval;
const typingSpeed = 50; // Controls typing animation speed

// Creates colorful typing animation for result messages
function typeMessage(message, element, iconElement) {
    let index = 0;
    element.textContent = '';
    
    // Animate bot icon color during typing
    colorInterval = setInterval(() => {
        iconElement.style.color = getRandomColor();
    }, 100);

    function type() {
        if (index < message.length) {
            element.textContent += message.charAt(index);
            index++;
            setTimeout(type, typingSpeed);
        } else {
            clearInterval(colorInterval);
            iconElement.style.color = '#00a67c'; // Reset to default color
        }
    }
    
    type();
}

// Displays randomized result message based on game outcome
function showResultMessage(resultType) {
    const messages = resultMessages[resultType === 'player' ? 'playerWins' : 
                    resultType === 'beano' ? 'beanoWins' : 'draws'];
    
    const message = messages[Math.floor(Math.random() * messages.length)];
    typeMessage(message, 
               document.getElementById('result-message'), 
               document.getElementById('result-bot-icon'));
}

// Helper function for random color generation
function getRandomColor() {
    return '#' + Math.floor(Math.random()*16777215).toString(16);
}